### ISSUE TITLE
📱 Custom templates

### ISSUE THREAD

**Issue by seichris** [better-feedback/roadmap#12]
## User story

As a dApp or DAO project I want to customize my Better board UI, so users feel like they are staying in the dApp.

## Tasks

- [ ] Write documentation on how to edit UI
- [ ] Write templates with default designs
- [ ] Offer customization-as-a-service

**Comment by seichris** [comment]
Let's run bounties to create new templates. The top voted template each month wins.

How to make it easy for others to create templates?
